var ma="function"==typeof Object.defineProperties?Object.defineProperty:function(h,t,C){h!=Array.prototype&&h!=Object.prototype&&(h[t]=C.value)},L="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function va(){va=function(){};L.Symbol||(L.Symbol=wa)}var xa=0;function wa(h){return"jscomp_symbol_"+(h||"")+xa++}
function ya(){va();var h=L.Symbol.iterator;h||(h=L.Symbol.iterator=L.Symbol("iterator"));"function"!=typeof Array.prototype[h]&&ma(Array.prototype,h,{configurable:!0,writable:!0,value:function(){return za(this)}});ya=function(){}}function za(h){var t=0;return Ja(function(){return t<h.length?{done:!1,value:h[t++]}:{done:!0}})}function Ja(h){ya();h={next:h};h[L.Symbol.iterator]=function(){return this};return h}
function Ka(h,t){ya();h instanceof String&&(h+="");var C=0,v={next:function(){if(C<h.length){var M=C++;return{value:t(M,h[M]),done:!1}}v.next=function(){return{done:!0,value:void 0}};return v.next()}};v[Symbol.iterator]=function(){return v};return v}for(var V=L,La=["Array","prototype","keys"],Qa=0;Qa<La.length-1;Qa++){var Ra=La[Qa];Ra in V||(V[Ra]={});V=V[Ra]}var Sa=La[La.length-1],Ta=V[Sa],Ua=Ta?Ta:function(){return Ka(this,function(h){return h})};
Ua!=Ta&&null!=Ua&&ma(V,Sa,{configurable:!0,writable:!0,value:Ua});
(function(){function h(a){this.g={j:new E(0,null),filter:new E(0,null)};this.Ja(a);k.call(this,w(this,this.M))}function t(a){this.g={j:new E(0,null)};this.Ka(a);k.call(this,w(this,this.M))}function C(a){this.Ia={j:g.D({u:function(){return new M}}),filter:g.D({u:function(){return new na}})};this.g={j:new E(0,null),filter:new E(0,null)};this.Ma(a);k.call(this,w(this,this.M))}function v(a){this.g={item:new E(0,null),ea:new E(0,null)};this.W=new H(!1,null);this.La(a);k.call(this,w(this,this.M))}function M(a){var b=
this;null==a&&(a={});a=a.items;this.Fa=null==a?l.S(null):l.S(a);this.vb=g.D({u:function(){for(var a=x.la,d=0,f=new z(b.B());0<f.list.length;){var e=f.next();a(e)&&++d}return d}});this.ub=g.D({u:function(){var a=b.sa(),d=b.B();return a<(null==d?0:d.length)}});this.l=new H(0,null);this.P=Aa.v();g.map(this.l,Ba.va(function(a){return 0<a}))}function x(a){var b=a.Yb;this.Ca=null==b?l.S(!1):l.S(b);this.Ea=l.S(a.description);a=a.Ua;var c;null==a?c=new Date:c=a;this.Ua=c;this.l=new H(0,null);this.P=Aa.v();
g["const"](this.Ua);g.map(this.l,Ba.va(function(a){return 0<a}))}function na(a){null==a&&(a={});this.options=ca.Xa([new oa("All",function(){return!0}),new oa("Active",x.la),new oa("Completed",x.na)]);this.Da=l.S((new z(this.options)).next().value);this.l=new H(0,null);this.P=Aa.v();g["const"](this.options);g.map(this.l,Ba.va(function(a){return 0<a}))}function H(a,b){this.value=a;var c;null==b?c=function(a,b){return a==b}:c=b;this.isEqual=c;this.Pa()}function da(a){var b=this;N.call(this,function(){b.v=
new O;return new I(a.u(),b.v)})}function W(a){this.Fb=new I(a,W.ca)}function N(a){this.xb=a}function z(a){this.list=[];null!=a&&this.list.push(a)}function J(a,b,c){this.value=b;this.length=a;this.gb=null==c?J.f:c}function Ca(){this.ka=[]}function Ma(){}function I(a,b){this.c=a;this.w=b}function oa(a,b){this.name=a;this.value=b}function O(){this.list=[]}function pa(a){this.u=a}function qa(a){this.value=a}function ra(a){this.value=a}function Na(){}function sa(){}function ea(a,b,c){null==a&&(a=500);
this.code=a;this.message=b;this.ma=c}function ta(a,b){if(null==a)throw new A("callback expected but null received");this.ra=a;this.list=b}function P(a){this.u=a}function Da(){}function Q(){}function A(a){this.Nb=a;Error.captureStackTrace&&Error.captureStackTrace(this,A)}function fa(){this.h={}}function Ea(a,b){this.map=a;this.keys=b;this.index=0;this.count=b.length}function X(){this.h={Z:{}}}function Oa(a,b){this.item=a;this.next=b}function Fa(){this.length=0}function Y(a){var b=this;this.id=setInterval(function(){b.bb()},
a)}function Ga(){}function n(){}function Z(a,b,c,d){null==b&&(b="span");F.call(this,c);this.content=a;this.tag=b;this.className=d}function q(){this.ab=0;this.pa=new fa}function Ha(a){this.Sa=new X;this.Ta=new fa;this.create=a;this.$a=new ha(a)}function ha(a){this.U=[];this.O=0;this.create=a}function E(a,b){var c;null==b?c=function(a,b){return a==b}:c=b;this.compare=c}function ia(){}function k(a){this.ha=k.o++;this.tb=new q;var b=this;K.call(this,g.D({u:function(){var c=b.tb.yb(a);ja.qb(c);return c}}))}
function K(a){this.Ga=a;F.call(this,"coconut-widget:"+K.oa++)}function F(a){this.t=":widget";this.k=a}function Pa(){}function ua(){}function Ia(){}function ka(){}function aa(){}function u(){}function B(){return Q.o(this,"")}function G(a,b){function c(){}c.prototype=a;a=new c;for(var d in b)a[d]=b[d];b.toString!==Object.prototype.toString&&(a.toString=b.toString);return a}function w(a,b){if(null==b)return null;null==b.H&&(b.H=Va++);var c;null==a.ta?a.ta={}:c=a.ta[b.H];null==c&&(c=b.bind(a),a.ta[b.H]=
c);return c}u.a=!0;u.Qb=function(a){switch(a.length){case 8:a=a.split(":");var b=new Date;b.setTime(0);b.setUTCHours(a[0]);b.setUTCMinutes(a[1]);b.setUTCSeconds(a[2]);return b;case 10:return a=a.split("-"),new Date(a[0],a[1]-1,a[2],0,0,0);case 19:return b=a.split(" "),a=b[0].split("-"),b=b[1].split(":"),new Date(a[0],a[1]-1,a[2],b[0],b[1],b[2]);default:throw new A("Invalid date format : "+a);}};u.ib=function(a,b){a=a.charCodeAt(b);if(a==a)return a};u.substr=function(a,b,c){if(null==c)c=a.length;else if(0>
c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};u.remove=function(a,b){b=a.indexOf(b);if(-1==b)return!1;a.splice(b,1);return!0};u.oa=function(a){return{Va:0,Qa:a,ba:function(){return this.Va<this.Qa.length},next:function(){return this.Qa[this.Va++]}}};Math.a=!0;aa.a=!0;aa.na=function(a){var b=[];if(null!=a){var c=Object.prototype.hasOwnProperty,d;for(d in a)"__id__"!=d&&"hx__closures__"!=d&&c.call(a,d)&&b.push(d)}return b};aa.jb=function(a,b){Object.prototype.hasOwnProperty.call(a,b)&&
delete a[b]};ka.a=!0;ka.kb=function(a,b){a=u.ib(a,b);return 8<a&&14>a?!0:32==a};ka.mb=function(a){for(var b=a.length,c=0;c<b&&ka.kb(a,b-c-1);)++c;return 0<c?u.substr(a,0,b-c):a};Ia.a=!0;Ia.lb=function(){var a=window.document.body,b=[];b.push(q.L("todomvc.ui.TodoListView",null,C.o,{}));a.appendChild(b[0].toElement())};ua.a=!0;Pa.a=!0;F.a=!0;F.prototype={I:function(){throw Error(""+this.t+" does not overwrite init method");},Ha:function(){return this.I()},Y:function(){}};K.a=!0;K.A=F;K.prototype=G(F.prototype,
{I:function(){this.$=g.b(this.Ga);this.F=n.A(this.$);this.Na(this.F);this.wb();return this.F},wb:function(){var a=this;this.sb=g.bind(this.Ga,null,function(b){b!=a.$&&a.rb(b)})},rb:function(a){this.F=n.hb(this.F,a,this.$);this.$=a;this.Oa(this.F)},toElement:function(){var a=this.F;return null==a?this.I():a},Wb:function(){},Na:function(){},Xb:function(){},Oa:function(){},Vb:function(){},Ub:function(){},Y:function(){var a=this.sb;null!=a&&a.K();F.prototype.Y.call(this);var b=null;b=function(a){var c=
0;for(a=a.m;c<(null==a?0:a.length);){var f=a[c];++c;":widget"==f.t?f.Y():b(f)}};b(this.$);this.F=null}});k.a=!0;k.f=[Pa];k.A=K;k.prototype=G(K.prototype,{$b:function(){return!0}});ia.a=!0;E.a=!0;E.f=[ia];E.prototype={J:function(){var a=this;if(null==this.C){if(null==this.data)this.C=new I(null,new O);else{var b=g.measure(this.data);this.C=new I(b.c,new O);this.link=b.w.handle((r=this.C.w,w(r,r.v)))}this.C.w.handle(p.R(function(){a.C=null}))}return new I(this.C.c,this.C.w)},observe:function(){return this},
setData:function(a){this.data=a;if(null!=this.C){var b=this.link;null!=b&&b.K();null!=a&&(b=g.Lb(function(){return g.measure(a)}),this.compare(b.c,this.C.c)?this.link=b.w.handle((r=this.C.w,w(r,r.v))):this.C.w.v(R.N))}}};ha.a=!0;ha.prototype={fa:function(){this.U.splice(this.O,this.U.length);this.O=0;return this.U.length},J:function(a){a=this.create(a,this.U[this.O]);this.O==this.U.length&&(this.U[this.O]=a);this.O++;return a}};Ha.a=!0;Ha.prototype={fa:function(){this.$a.fa();for(var a=this.Ta,b=
[],c=a.keys();c.ba();){var d=c.next();0==(null!=S[d]?a.ja(d):a.h[d]).fa()&&b.push(d)}for(c=0;c<b.length;)d=b[c],++c,a.remove(d);a=this.Sa;b=[];for(c=a.keys();c.ba();)d=c.next(),0==a.h[d.H].fa()&&b.push(d);for(c=0;c<b.length;)d=b[c],++c,a.remove(d)},J:function(a,b){if(null==b)b=this.$a;else{if("string"===typeof b){var c=this.Ta,d=null!=S[b]?c.ja(b):c.h[b];null==d&&(d=new ha(this.create),null!=S[b]?c.fb(b,d):c.h[b]=d)}else c=this.Sa,d=c.h[b.H],null==d&&(d=new ha(this.create),c.set(b,d));b=d}return b.J(a)}};
q.a=!0;q.L=function(a,b,c,d){var f=q.stack;f=f.length?f[f.length-1][0]:new q;var e=f.pa;e=null!=S[a]?e.ja(a):e.h[a];null==e?(f=f.pa,c=new Ha(c),null!=S[a]?f.fb(a,c):f.h[a]=c,a=c):a=e;return a.J(d,b)};q.prototype={yb:function(a){var b=this;if(0<q.stack.length&&q.stack[q.stack.length-1][0]==this)return a();var c=Array(1);c[0]=this;q.stack.push(c);this.ab++;return ea.o(a,function(){u.remove(q.stack,c);if(!--b.ab){var a=b.pa;for(a=new Ea(a,a.Ra());a.ba();)a.next().fa()}})}};var Wa={a:!0,Gb:function(a){return a}},
m={a:!0,i:function(a){for(var b=[],c=0;c<a.length;){var d=a[c];++c;null!=d&&b.push(d)}return b}},ba={a:!0,T:function(a){return a.trim()}};Z.a=!0;Z.create=function(a){return""==a.content&&1!=a.force?null:new Z(a.content,a.tag,a.key,a.className)};Z.f=F;Z.prototype=G(F.prototype,{I:function(){null==this.element&&(this.element=window.document.createElement(this.tag),this.element.innerHTML=this.content,null!=this.className&&(this.element.className=this.className));return this.element},Ha:function(a,b){a=
a instanceof Z?a:null;return null==a?this.I():a.tag==this.tag?(this.element=b,this.className!=a.className&&(this.element.className=this.className),this.content!=a.content&&(this.element.innerHTML=this.content),b):this.I()}});n.a=!0;n.hb=function(a,b,c){function d(b){f=b;null!=a.parentNode&&a.parentNode.replaceChild(f,a)}if(b==c)return a;var f=a,e=":widget"==c.t;switch(":widget"==b.t){case !1:switch(e){case !1:if(b.t!=c.t)d(n.A(b));else if(":text"==b.t)b=":text"==b.t?b.k:null,(":text"==c.t?c.k:null)!=
b&&(a.nodeValue=b);else if(null!=(":native"==b.t?b.c[":native"]:null))d(":native"==b.t?b.c[":native"]:null);else{n.ya(a,b.c,c.c);e=b.m;c=c.m;c=null==c?[]:c.slice();var g=a.childNodes;b=null==e?0:e.length;for(var h=c.length,m={},p={},D=0;D<(null==e?0:e.length);){var l=e[D];++D;null==l.k||p[l.k]||(p[l.k]=!0)}for(D=0;D<h;){l=D++;var k=c[l].k;null!=k&&p[k]&&!Object.prototype.hasOwnProperty.call(m,k)&&(m[k]=l)}D=0;p=[];for(l=0;l<b;){k=l++;k=e[k];var q=m[k.k];if(null==q){for(;D<h;)if(q=c[D],null==q||Object.prototype.hasOwnProperty.call(m,
q.k))++D;else break;q=D<h?D++:D}else aa.jb(m,k.k);var r=g[q];if(null==r)k=n.A(k);else{var t=c[q];c[q]=null;k=n.hb(r,k,t)}p.push(k)}e=0;for(g=p.length;e<g;)h=e++,m=p[h],m!=a.childNodes[h]&&a.insertBefore(m,a.childNodes[h]);e=b;for(g=a.childNodes.length;e<g;)e++,a.removeChild(a.childNodes[b]);for(b=0;b<c.length;)e=c[b],++b,null!=e&&":widget"==e.t&&(":widget"==e.t?e:null).Y()}break;case !0:(":widget"==c.t?c:null).Y(),d(n.A(b))}break;case !0:switch(e){case !1:d((":widget"==b.t?b:null).I());break;case !0:d((":widget"==
b.t?b:null).Ha(":widget"==c.t?c:null,a))}}return f};n.nb=function(a,b,c,d){switch(b){case "attributes":n.za(a,c,d,n.ob);break;case "key":break;default:null==c?delete a[b]:a[b]=c}};n.ob=function(a,b,c){null==c?a.removeAttribute(b):a.setAttribute(b,c)};n.pb=function(a,b,c,d){d!=c&&n.nb(a,b,c,d)};n.ya=function(a,b,c){n.za(a,b,c,n.pb)};n.za=function(a,b,c,d){var f={};null==b&&(b=n.f);null==c&&(c=n.f);for(var e=0,g=Object.getOwnPropertyNames(b);e<g.length;){var h=g[e];++e;f[h]=!0}e=0;for(g=Object.getOwnPropertyNames(c);e<
g.length;)h=g[e],++e,f[h]=!0;e=0;for(f=Object.getOwnPropertyNames(f);e<f.length;)g=f[e],++e,d(a,g,b[g],c[g])};n.A=function(a){if(":widget"==a.t)return(":widget"==a.t?a:null).I();if(":text"==a.t)return window.document.createTextNode(":text"==a.t?a.k:null);var b=":native"==a.t?a.c[":native"]:null;if(null==b){b=window.document.createElement(a.t);n.ya(b,a.c,null);var c=0;for(a=a.m;c<(null==a?0:a.length);){var d=a[c];++c;null!=d&&b.appendChild(n.A(d))}}return b};var y={ia:!0,qa:["CFunction","Module","FilePos",
"Method","LocalFunction"],Aa:["CFunction",0]};y.Aa.toString=B;y.Aa.f=y;y.Tb=function(a){a=["Module",1,a];a.f=y;a.toString=B;return a};y.Pb=function(a,b,c,d){a=["FilePos",2,a,b,c,d];a.f=y;a.toString=B;return a};y.Sb=function(a,b){a=["Method",3,a,b];a.f=y;a.toString=B;return a};y.Rb=function(a){a=["LocalFunction",4,a];a.f=y;a.toString=B;return a};Ga.a=!0;Y.a=!0;Y.L=function(a,b){var c=new Y(b);c.bb=function(){c.stop();a()};return c};Y.prototype={stop:function(){null!=this.id&&(clearInterval(this.id),
this.id=null)},bb:function(){}};Fa.a=!0;Fa.prototype={push:function(a){this.h=a=new Oa(a,this.h);null==this.q&&(this.q=a);this.length++},first:function(){return null==this.h?null:this.h.item},pop:function(){if(null==this.h)return null;var a=this.h.item;this.h=this.h.next;null==this.h&&(this.q=null);this.length--;return a}};Oa.a=!0;X.a=!0;X.ca=[Ga];X.prototype={set:function(a,b){var c=a.H||(a.H=++X.count);this.h[c]=b;this.h.Z[c]=a},remove:function(a){a=a.H;if(null==this.h.Z[a])return!1;delete this.h[a];
delete this.h.Z[a];return!0},keys:function(){var a=[],b;for(b in this.h.Z)this.h.hasOwnProperty(b)&&a.push(this.h.Z[b]);return u.oa(a)}};var ja={ia:!0,qa:["Some","None"],qb:function(a){a=["Some",0,a];a.f=ja;a.toString=B;return a},Ba:["None",1]};ja.Ba.toString=B;ja.Ba.f=ja;Ea.a=!0;Ea.prototype={ba:function(){return this.index<this.count},next:function(){var a=this.map,b=this.keys[this.index++];return null!=S[b]?a.ja(b):a.h[b]}};fa.a=!0;fa.ca=[Ga];fa.prototype={fb:function(a,b){null==this.G&&(this.G=
{});this.G["$"+a]=b},ja:function(a){return null==this.G?null:this.G["$"+a]},remove:function(a){if(null!=S[a]){a="$"+a;if(null==this.G||!this.G.hasOwnProperty(a))return!1;delete this.G[a]}else{if(!this.h.hasOwnProperty(a))return!1;delete this.h[a]}return!0},keys:function(){return u.oa(this.Ra())},Ra:function(){var a=[],b;for(b in this.h)this.h.hasOwnProperty(b)&&a.push(b);if(null!=this.G)for(b in this.G)36==b.charCodeAt(0)&&a.push(b.substr(1));return a}};A.a=!0;A.ya=function(a){return a instanceof
Error?a:new A(a)};A.A=Error;A.prototype=G(Error.prototype,{});Q.a=!0;Q.o=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.a||a.ia)&&(c="object");switch(c){case "function":return"<function>";case "object":if(a instanceof Array){if(a.f){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";for(var d=2,f=a.length;d<f;){var e=d++;c=2!=e?c+(","+Q.o(a[e],b)):c+Q.o(a[e],b)}return c+")"}c=a.length;d="[";b+="\t";for(f=0;f<c;)e=f++,d+=(0<e?",":"")+Q.o(a[e],b);return d+
"]"}try{d=a.toString}catch(Xa){return"???"}if(null!=d&&d!=Object.toString&&"function"==typeof d&&(c=a.toString(),"[object Object]"!=c))return c;c=null;d="{\n";b+="\t";f=null!=a.hasOwnProperty;for(c in a)f&&!a.hasOwnProperty(c)||"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=d.length&&(d+=", \n"),d+=b+c+" : "+Q.o(a[c],b));b=b.substring(1);return d+("\n"+b+"}");case "string":return a;default:return String(a)}};var p={a:!0,s:function(a,b){1E3>p.depth?(p.depth++,
a(b),p.depth--):p.defer(function(){p.s(a,b)})},R:function(a){return function(){a()}},defer:function(a){Y.L(a,0)}};Da.a=!0;P.a=!0;P.f=[Da];P.prototype={K:function(){null!=this.u&&this.u()}};ta.a=!0;ta.f=[Da];ta.prototype={clear:function(){this.ra=this.list=null},K:function(){var a=this.list;null!=a&&(this.clear(),u.remove(a,this))}};var T={a:!0,add:function(a,b){b=new ta(b,a);a.push(b);return b},s:function(a,b){var c=0;for(a=a.slice();c<a.length;){var d=a[c];++c;null!=d.ra&&p.s(d.ra,b)}},clear:function(a){var b=
0;for(a=a.splice(0,a.length);b<a.length;){var c=a[b];++b;c.clear()}}};ea.a=!0;ea.o=function(a,b){try{return a()}finally{b()}return null};ea.prototype={Ib:function(){return this.ma.className+"."+this.ma.Zb+":"+this.ma.lineNumber},toString:function(){var a="Error#"+this.code+": "+this.message;null!=this.ma&&(a+=" @ "+this.Ib());return a}};sa.a=!0;var R={ia:!0,qa:["Noise"],N:["Noise",0]};R.N.toString=B;R.N.f=R;Na.a=!0;ra.a=!0;ra.f=[Na];ra.prototype={get:function(){return this.value}};qa.a=!0;qa.f=[sa];
qa.prototype={handle:function(a){p.s(a,this.value.get());return null}};pa.a=!0;pa.f=[sa];pa.prototype={handle:function(a){return this.u(a)}};O.a=!0;O.ca=[sa];O.prototype={handle:function(a){var b=this.list;return null==b?(p.s(a,this.result),null):T.add(b,a)},v:function(a){if(null==this.list)return!1;var b=this.list;this.list=null;this.result=a;T.s(b,a);T.clear(b);return!0}};oa.a=!0;var U={ia:!0,qa:["Success","Failure"],V:function(a){a=["Success",0,a];a.f=U;a.toString=B;return a},Ob:function(a){a=
["Failure",1,a];a.f=U;a.toString=B;return a}};I.a=!0;var la={a:!0,da:function(a){return new qa(new ra(a))}},Aa={a:!0,v:function(){return new Ca}};Ma.a=!0;Ca.a=!0;Ca.ca=[Ma];var ca={a:!0,Hb:function(a,b){return null==a?new J(1,b):new J(a.length+1,b,[a])},filter:function(a,b){return null==a?null:a.filter(b)},Xa:function(a){for(var b=null,c=0,d=a.length;0<d--;)b=new J(++c,a[d],null==b?J.f:[b]);return b}};J.a=!0;J.prototype={filter:function(a){for(var b=new z(this),c=[];0<b.list.length;){var d=b.next(),
f=a(d);0<f&&c.push(d);if(3==(f&3))break}return ca.Xa(c)}};z.a=!0;z.prototype={ba:function(){return 0<this.list.length},next:function(){var a=this.list.pop();if(null==a)return null;for(var b=-a.gb.length;0>b;){var c=b++;this.list.push(a.gb[-c-1])}return a.value}};var g={a:!0,b:function(a){return g.measure(a).c},map:function(a,b){return g.create(function(){var c=g.measure(a);return new I(b(c.c),c.w)})},measure:function(a){var b=g.stack.first();g.stack.push(a);a=a.J();b=b instanceof da?b:null;null!=
b&&a.w.handle(p.R(w(b,b.Eb)));g.stack.pop();return a},bind:function(a,b,c){if(null==b)var d=c;else if(null==b.Ab)d=c;else{var f=b.Ab,e=!0,h=null;d=function(a){e?(e=!1,p.s(c,a)):f(h,a)||p.s(c,a);h=a}}if(null==b){var m=!1,n=!0,k=null,l=null,q=function(){if(n){var b=g.measure(a);p.s(d,b.c);m=!1;l=b.w.handle(k)}};b=function(){m||(m=!0,g.wa(q))};k=p.R(b);b();return new P(function(){n&&(n=!1,null!=l&&l.K())})}if(null==b.Bb){var r=!1,t=!0,v=null,u=null,C=function(){if(t){var b=g.measure(a);p.s(d,b.c);r=
!1;u=b.w.handle(v)}};b=function(){r||(r=!0,g.wa(C))};v=p.R(b);b();return new P(function(){t&&(t=!1,null!=u&&u.K())})}if(0==b.Bb){var w=!1,x=!0,A=null,y=null,E=function(){if(x){var b=g.measure(a);p.s(d,b.c);w=!1;y=b.w.handle(A)}};b=function(){w||(w=!0,g.wa(E))};A=p.R(b);b();return new P(function(){x&&(x=!1,null!=y&&y.K())})}var z=null,B=null;B=function(){var b=g.measure(a);p.s(d,b.c);z=b.w.handle(B)};B(R.N);return new P(function(){null!=z&&z.K()})},wa:function(a){var b=g.ga;b?(b.push(a),g.cb()):a()},
cb:function(){g.ua||(g.ua=!0,g.Db?window.requestAnimationFrame(function(){g.eb()}):p.defer(g.eb))},eb:function(){g.ua=!1;g.Mb()},Mb:function(a){null==a&&(a=.01);for(a=(new Date).getTime()/1E3+a;;){var b=g.ga;g.ga=[];for(var c=0;c<b.length;){var d=b[c];++c;d()}if(!(0<g.ga.length&&(new Date).getTime()/1E3<a))break}return 0<g.ga.length?(g.cb(),!0):!1},create:function(a){return new N(a)},D:function(a){return new da(a)},"const":function(a){return new W(a)},Lb:function(a){g.stack.push(null);return ea.o(a,
(r=g.stack,w(r,r.pop)))}};N.a=!0;N.f=[ia];N.prototype={Jb:function(){this.cache=null},J:function(){for(var a=0,b=null;null==this.cache;){var c=this.cache=this.xb();if(b==c)throw new A("Polling loops on the same value");b=c;c.w.handle(w(this,this.Jb));if(100<=a++)throw new A("Polling not concluded after 100 iterations");}return this.cache}};var Ba={a:!0,va:function(a){return a}};W.a=!0;W.f=[ia];W.prototype={J:function(){return this.Fb}};da.a=!0;da.A=N;da.prototype=G(N.prototype,{Eb:function(){this.v.v(R.N)}});
var l={a:!0,b:function(a){return g.b(a)},S:function(a){return new H(a,null)}};H.a=!0;H.f=[ia];H.prototype={J:function(){return this.next},Pa:function(){this.v=new O;this.next=new I(this.value,this.v)},set:function(a){this.isEqual(a,this.value)||(this.value=a,a=this.v,this.Pa(),a.v(R.N))}};na.a=!0;na.f=[ua];na.prototype={matches:function(a){return this.Ya()(a)},toggle:function(a){var b=this,c=function(){for(var c=new z(b.options);0<c.list.length;)if(c.next().value==a)return la.da(U.V({Wa:a}));return la.da(U.V({}))}(),
d=!0,f=!1;c.handle(function(a){f=!0;if(!d){var c=l.b(b.l)-1;b.l.set(c)}switch(a[1]){case 0:b.X(a[2]);break;case 1:T.s(b.P.ka,a[2])}});f||(d=!1);d||this.l.set(l.b(this.l)+1);return c},la:function(a){return a==this.Ya()},Ya:function(){return l.b(this.Da)},X:function(a){for(var b={},c=0,d=aa.na(a);c<d.length;){var f=d[c];++c;var e=Array(1);e[0]=a[f];b[f]=e}null!=b.Wa&&this.Da.set(b.Wa[0])}};x.a=!0;x.f=[ua];x.create=function(a){return new x({description:a})};x.la=function(a){return!a.aa()};x.na=function(a){return a.aa()};
x.prototype={aa:function(){return l.b(this.Ca)},xa:function(a){this.Ca.set(a);return a},Za:function(){return l.b(this.Ea)},Kb:function(a){this.Ea.set(a);return a}};M.a=!0;M.f=[ua];M.prototype={add:function(a){var b=this;a=la.da(U.V({items:ca.Hb(b.B(),x.create(a))}));var c=!0,d=!1;a.handle(function(a){d=!0;if(!c){var e=l.b(b.l)-1;b.l.set(e)}switch(a[1]){case 0:b.X(a[2]);break;case 1:T.s(b.P.ka,a[2])}});d||(c=!1);c||this.l.set(l.b(this.l)+1);return a},"delete":function(a){var b=this,c=la.da(U.V({items:ca.filter(b.B(),
function(b){return b!=a?1:0})})),d=!0,f=!1;c.handle(function(a){f=!0;if(!d){var c=l.b(b.l)-1;b.l.set(c)}switch(a[1]){case 0:b.X(a[2]);break;case 1:T.s(b.P.ka,a[2])}});f||(d=!1);d||this.l.set(l.b(this.l)+1);return c},zb:function(){var a=this,b=la.da(U.V({items:ca.filter(a.B(),function(a){return a.aa()?0:1})})),c=!0,d=!1;b.handle(function(b){d=!0;if(!c){var e=l.b(a.l)-1;a.l.set(e)}switch(b[1]){case 0:a.X(b[2]);break;case 1:T.s(a.P.ka,b[2])}});d||(c=!1);c||this.l.set(l.b(this.l)+1);return b},B:function(){return l.b(this.Fa)},
sa:function(){return g.b(this.vb)},Cb:function(){return g.b(this.ub)},X:function(a){for(var b={},c=0,d=aa.na(a);c<d.length;){var f=d[c];++c;var e=Array(1);e[0]=a[f];b[f]=e}null!=b.items&&this.Fa.set(b.items[0])}};v.a=!0;v.o=function(a,b){null==b?b=new v(a):b.La(a);return b};v.A=k;v.prototype=G(k.prototype,{M:function(){var a=this,b=[],c={title:""+a.ha,className:ba.T("todo-item"),attributes:{"data-completed":g.b(a.g.item.observe()).aa()?"":void 0,"data-editing":l.b(a.W)?"":void 0}},d=[];m.i(d);var f=
{name:"completed",type:"checkbox",checked:g.b(a.g.item.observe()).aa(),onchange:function(b){g.b(a.g.item.observe()).xa(b.currentTarget.checked)}};d.push({t:"input",k:f?f.key:null,c:f,m:null});if(l.b(this.W))f={name:"description",type:"text",value:g.b(a.g.item.observe()).Za(),onchange:function(b){b=ka.mb(b.currentTarget.value);""==b?g.b(a.g.ea.observe())(g.b(a.g.item.observe())):g.b(a.g.item.observe()).Kb(b)},onblur:function(){a.W.set(!1)}},d.push({t:"input",k:f?f.key:null,c:f,m:null});else{f={className:ba.T("description"),
ondblclick:function(){a.W.set(!0)}};var e=[];m.i(e);e.push({t:":text",k:g.b(this.g.item.observe()).Za(),c:n.f});e=m.i(e);d.push({t:"span",k:f?f.key:null,c:f,m:e});f={className:ba.T("delete"),onclick:function(){g.b(a.g.ea.observe())(g.b(a.g.item.observe()))}};e=[];m.i(e);e.push({t:":text",k:"Delete",c:n.f});e=m.i(e);d.push({t:"button",k:f?f.key:null,c:f,m:e})}d=m.i(d);b.push({t:"li",k:c?c.key:null,c:c,m:d});return b[0]},Oa:function(){l.b(this.W)&&this.F.querySelector('input[type="text"]').focus()},
toString:function(){return"TodoItemView#"+this.ha},La:function(a){this.g.item.setData(a.item);this.g.ea.setData(a.ea)}});C.a=!0;C.o=function(a,b){null==b?b=new C(a):b.Ma(a);return b};C.A=k;C.prototype=G(k.prototype,{M:function(){var a=this,b=[],c=ba.T("todo-list"),d=g.b(a.g.j.observe()).B();c={className:c,attributes:{"data-empty":0==(null==d?0:d.length)?"":void 0}};d=[];m.i(d);var f={},e=[];m.i(e);e.push({t:":text",k:"todos",c:n.f});e=m.i(e);d.push({t:"h1",k:f?f.key:null,c:f,m:e});var k=this;d.push(q.L("todomvc.ui._TodoListView.Header",
null,t.o,{j:g.D({u:function(){return g.b(k.g.j.observe())}})}));f=g.b(this.g.j.observe()).B();if(0<(null==f?0:f.length)){f={};e=[];m.i(e);for(var l=new z(g.b(this.g.j.observe()).B());0<l.list.length;){var p=[l.next()];g.b(this.g.filter.observe()).matches(p[0])&&e.push(q.L("todomvc.ui.TodoItemView",Wa.Gb(p[0]),v.o,{item:g.D({u:function(a){return function(){return a[0]}}(p)}),ea:g.D({u:function(b){return function(){return function(b){return function(){g.b(a.g.j.observe())["delete"](b[0])}}(b)}}(p)})}))}e=
m.i(e);d.push({t:"ol",k:f?f.key:null,c:f,m:e});var r=this;d.push(q.L("todomvc.ui._TodoListView.Footer",null,h.o,{j:g.D({u:function(){return g.b(r.g.j.observe())}}),filter:g.D({u:function(){return g.b(r.g.filter.observe())}})}))}d=m.i(d);b.push({t:"div",k:c?c.key:null,c:c,m:d});return b[0]},toString:function(){return"TodoListView#"+this.ha},Ma:function(a){var b=a.j;this.g.j.setData(null==b?this.Ia.j:b);a=a.filter;this.g.filter.setData(null==a?this.Ia.filter:a)}});t.a=!0;t.o=function(a,b){null==b?b=
new t(a):b.Ka(a);return b};t.A=k;t.prototype=G(k.prototype,{M:function(){var a=this,b=[],c={},d=[];m.i(d);var f={type:"text",placeholder:"What needs to be done?",onkeypress:function(b){13==b.keyCode&&(g.b(a.g.j.observe()).add(b.currentTarget.value),b.currentTarget.value="")}};d.push({t:"input",k:f?f.key:null,c:f,m:null});f=g.b(this.g.j.observe()).B();if(0<(null==f?0:f.length))if(0<g.b(this.g.j.observe()).sa()){f={className:ba.T("mark-all"),onclick:function(){for(var b=new z(g.b(a.g.j.observe()).B());0<
b.list.length;)b.next().xa(!0)}};var e=[];m.i(e);e.push({t:":text",k:"Mark all as completed",c:n.f});e=m.i(e);d.push({t:"button",k:f?f.key:null,c:f,m:e})}else f={className:ba.T("unmark-all"),onclick:function(){for(var b=new z(g.b(a.g.j.observe()).B());0<b.list.length;)b.next().xa(!1)}},e=[],m.i(e),e.push({t:":text",k:"Unmark all as completed",c:n.f}),e=m.i(e),d.push({t:"button",k:f?f.key:null,c:f,m:e});d=m.i(d);b.push({t:"header",k:c?c.key:null,c:c,m:d});return b[0]},Na:function(){var a=this;r=Y.L(function(){a.F.querySelector("header input").focus()},
10);w(r,r.stop)},toString:function(){return"Header#"+this.ha},Ka:function(a){this.g.j.setData(a.j)}});h.a=!0;h.o=function(a,b){null==b?b=new h(a):b.Ja(a);return b};h.A=k;h.prototype=G(k.prototype,{M:function(){var a=this,b=[],c={},d=[];m.i(d);var f={},e=[];m.i(e);var h=g.b(this.g.j.observe()).sa();1==h?e.push({t:":text",k:"1 item",c:n.f}):(e.push({t:":text",k:null==h?"null":""+h,c:n.f}),e.push({t:":text",k:" items",c:n.f}));e.push({t:":text",k:" left",c:n.f});e=m.i(e);d.push({t:"span",k:f?f.key:null,
c:f,m:e});f={};e=[];m.i(e);for(h=new z(g.b(this.g.filter.observe()).options);0<h.list.length;){var k=[h.next()],l={onclick:function(b){return function(){g.b(a.g.filter.observe()).toggle(b[0].value)}}(k),attributes:{"data-active":g.b(a.g.filter.observe()).la(k[0].value)?"":void 0}},q=[];m.i(q);q.push({t:":text",k:k[0].name,c:n.f});k=m.i(q);e.push({t:"button",k:l?l.key:null,c:l,m:k})}e=m.i(e);d.push({t:"menu",k:f?f.key:null,c:f,m:e});g.b(this.g.j.observe()).Cb()&&(f={onclick:p.R((r=g.b(a.g.j.observe()),
w(r,r.zb)))},e=[],m.i(e),e.push({t:":text",k:"Clear Completed",c:n.f}),e=m.i(e),d.push({t:"button",k:f?f.key:null,c:f,m:e}));d=m.i(d);b.push({t:"footer",k:c?c.key:null,c:c,m:d});return b[0]},toString:function(){return"Footer#"+this.ha},Ja:function(a){this.g.j.setData(a.j);this.g.filter.setData(a.filter)}});var r,Va=0;String.a=!0;Array.a=!0;Date.a=["Date"];X.count=0;var S={};Object.defineProperty(A.prototype,"message",{get:function(){return String(this.Nb)}});K.oa=0;k.o=0;q.stack=[];n.f={};p.depth=
0;J.f=[];g.stack=new Fa;g.ga=[];g.Db="undefined"!=typeof window&&"requestAnimationFrame"in window;g.ua=!1;W.ca=function(){return new pa(function(){return null})}(this);Ia.lb()})();
